name: Auto Commit 3-4 Times Daily

on:
  schedule:
    - cron: '5 0 * * *'
    - cron: '10 6 * * *'
    - cron: '15 12 * * *'
    - cron: '20 18 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make a dummy change
        run: |
          echo "Update on $(date)" >> auto.txt

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add auto.txt
          git commit -m "Auto commit: $(date)" || echo "Nothing to commit"
          git push
